((nil . ((indent-tabs-mode . nil)))
 (nxml-mode . ((fill-column . 100)
	       (ispell-local-dictionary . "british")
               (mode . auto-fill)
               (mode . flyspell)))
 (xml-mode . ((mode . nxml))))
