# SPDX-FileCopyrightText: 2009- Diego Elio Pettenò
#
# SPDX-License-Identifier: MIT

name: Merge master branch to published
on:
  push:
    branches:
      - 'master'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to published branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'published'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
